name: Docs

on:
  push:
    branches:
      - master
    paths:
      - src/**
  pull_request:
    paths:
      - src/**
  workflow_dispatch:
    branches:
      - master
    inputs:
      deploy:
        description: Deploy ?
        required: true
        default: false
        type: boolean

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm
        id: npm-install
        uses: npm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Get npm store
        id: npm-store
        shell: bash
        run: echo "STORE_PATH=$(npm store path)" >> $GITHUB_OUTPUT

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-store.outputs.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-store-

      - name: Install dependencies
        run: npm i

      - name: Build docs
        run: npm run build

      - name: Deploy docs
        if: ${{ github.event_name == 'push' || inputs.deploy }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
